//if(score = 1){sprite_index = spr_score0}
//if(score = 2){sprite_index = spr_score0}
//if(score = 3){sprite_index = spr_score0}
//if(score = 4){sprite_index = spr_score0}
//if(score = 5){sprite_index = spr_score0}
//if(score = 6){sprite_index = spr_score0}
//if(score = 7){sprite_index = spr_score0}
//if(score = 8){sprite_index = spr_score0}
//if(score = 9){sprite_index = spr_score0}
//if(score = 10){sprite_index = spr_score0}
//if(score = 11){sprite_index = spr_score0}
//if(score = 12){sprite_index = spr_score0}
//if(score = 13){sprite_index = spr_score0}
//if(score = 14){sprite_index = spr_score0}
//if(score = 15){sprite_index = spr_score0}
//if(score = 16){sprite_index = spr_score0}
//if(score = 17){sprite_index = spr_score0}
//if(score = 18){sprite_index = spr_score0}
//if(score = 19){sprite_index = spr_score0}
//if(score = 20){sprite_index = spr_score0}
//if(score = 21){sprite_index = spr_score0}
//if(score = 22){sprite_index = spr_score0}
//if(score = 23){sprite_index = spr_score0}
//if(score = 24){sprite_index = spr_score0}
//if(score = 25){sprite_index = spr_score0}
//if(score = 26){sprite_index = spr_score0}
//if(score = 27){sprite_index = spr_score0}
//if(score = 28){sprite_index = spr_score0}
//if(score = 29){sprite_index = spr_score0}
//if(score = 30){sprite_index = spr_score0}
//if(score = 31){sprite_index = spr_score0}
//if(score = 32){sprite_index = spr_score0}
//if(score = 33){sprite_index = spr_score0}
//if(score = 34){sprite_index = spr_score0}
//if(score = 35){sprite_index = spr_score0}
//if(score = 36){sprite_index = spr_score0}
//if(score = 37){sprite_index = spr_score0}
//if(score = 38){sprite_index = spr_score0}
//if(score = 39){sprite_index = spr_score0}
//if(score = 40){sprite_index = spr_score0}
//if(score = 41){sprite_index = spr_score0}
//if(score = 42){sprite_index = spr_score0}
//if(score = 43){sprite_index = spr_score0}
//if(score = 44){sprite_index = spr_score0}
//if(score = 45){sprite_index = spr_score0}
//if(score = 46){sprite_index = spr_score0}
//if(score = 47){sprite_index = spr_score0}
//if(score = 48){sprite_index = spr_score0}
//if(score = 49){sprite_index = spr_score0}
//if(score >= 50){sprite_index = spr_score0}

//x = obj_player.x -32
//y = obj_player.y -34
